# Generated by Django 3.1 on 2020-08-14 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], default=',', max_length=10)),
                ('string_character', models.CharField(choices=[('"', 'Double-quote (")'), ('*', 'Asterisk (*)')], default='"', max_length=10)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('full_name', 'Full name'), ('email', 'Email'), ('domain_name', 'Domain name'), ('phone_number', 'Phone number'), ('company_name', 'Company Name'), ('address', 'Address')], max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_columns', to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rows', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready')], default='processing', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='schemas.schema')),
            ],
        ),
    ]
